#baseURL = "http://www.mcknightsolution.io"
baseURL = "https://djmcknight.github.io/blog/"
languageCode = "en-us"
title = "Derek McKnight"
theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Welcome to my blog"
  facebook = ""
  twitter = "https://twitter.com/derekjmcknight"
  youtube = ""
  github = "https://github.com/djmcknight"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/derekjmcknight"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/cinci.jpg"
  recent_posts_number = 2